# Generated by Django 4.2.8 on 2025-12-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Employer name (original from DOL data)', max_length=255)),
                ('name_normalized', models.CharField(db_index=True, help_text='Normalized name for matching (lowercase, cleaned)', max_length=255)),
                ('city', models.CharField(blank=True, help_text='Employer city', max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, help_text='Employer state (2-letter code)', max_length=2)),
                ('total_lca_count', models.IntegerField(default=0, help_text='Total H-1B LCA applications')),
                ('total_perm_count', models.IntegerField(default=0, help_text='Total PERM applications')),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Average salary across all records', max_digits=12, null=True)),
            ],
            options={
                'db_table': 'salary_employer',
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, help_text='DOL case number (unique identifier)', max_length=50, unique=True)),
                ('visa_program', models.CharField(choices=[('h1b', 'H-1B (Specialty Occupation)'), ('h1b1', 'H-1B1 (Chile/Singapore)'), ('e3', 'E-3 (Australia)'), ('perm', 'PERM (Permanent Labor Certification)')], db_index=True, help_text='Visa program type (H-1B, PERM, etc.)', max_length=10)),
                ('case_status', models.CharField(blank=True, choices=[('certified', 'Certified'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn'), ('certified_withdrawn', 'Certified-Withdrawn')], help_text='Case status (Certified, Denied, etc.)', max_length=30)),
                ('employer_name', models.CharField(db_index=True, help_text='Employer name from DOL data', max_length=255)),
                ('job_title', models.CharField(db_index=True, help_text='Job title', max_length=255)),
                ('soc_code', models.CharField(blank=True, db_index=True, help_text='Standard Occupational Classification code', max_length=20)),
                ('soc_title', models.CharField(blank=True, help_text='SOC occupation title', max_length=255)),
                ('worksite_city', models.CharField(blank=True, help_text='Work location city', max_length=100)),
                ('worksite_state', models.CharField(blank=True, db_index=True, help_text='Work location state (2-letter code)', max_length=2)),
                ('wage_from', models.DecimalField(decimal_places=2, help_text='Wage offer (from/minimum)', max_digits=12)),
                ('wage_to', models.DecimalField(blank=True, decimal_places=2, help_text='Wage offer (to/maximum, if range)', max_digits=12, null=True)),
                ('wage_unit', models.CharField(choices=[('year', 'Per Year'), ('month', 'Per Month'), ('bi_weekly', 'Bi-Weekly'), ('week', 'Per Week'), ('hour', 'Per Hour')], default='year', help_text='Unit of pay (year, month, hour, etc.)', max_length=20)),
                ('wage_annual', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Annualized wage (calculated)', max_digits=12, null=True)),
                ('prevailing_wage', models.DecimalField(blank=True, decimal_places=2, help_text='Prevailing wage for the position', max_digits=12, null=True)),
                ('prevailing_wage_unit', models.CharField(blank=True, choices=[('year', 'Per Year'), ('month', 'Per Month'), ('bi_weekly', 'Bi-Weekly'), ('week', 'Per Week'), ('hour', 'Per Hour')], help_text='Prevailing wage unit', max_length=20)),
                ('case_submitted', models.DateField(blank=True, db_index=True, help_text='Date case was submitted', null=True)),
                ('decision_date', models.DateField(blank=True, db_index=True, help_text='Date of decision', null=True)),
                ('employment_start', models.DateField(blank=True, help_text='Employment start date', null=True)),
                ('employment_end', models.DateField(blank=True, help_text='Employment end date', null=True)),
                ('fiscal_year', models.IntegerField(db_index=True, help_text='Fiscal year of the record')),
                ('source_file', models.CharField(blank=True, help_text='Source CSV file name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='models.employer')),
            ],
            options={
                'db_table': 'salary_record',
                'ordering': ['-decision_date', '-case_submitted'],
            },
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['name_normalized'], name='salary_empl_name_no_6de4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['state'], name='salary_empl_state_a66a28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('name_normalized', 'city', 'state')},
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employer_name', 'job_title'], name='salary_reco_employe_c93e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['job_title', 'worksite_state'], name='salary_reco_job_tit_7b8349_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['soc_code', 'worksite_state'], name='salary_reco_soc_cod_8cdf26_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['visa_program', 'fiscal_year'], name='salary_reco_visa_pr_044b05_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['worksite_state', 'fiscal_year'], name='salary_reco_worksit_fe8724_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['wage_annual', 'visa_program'], name='salary_reco_wage_an_95e1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['decision_date'], name='salary_reco_decisio_e82d25_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['fiscal_year', 'decision_date'], name='salary_reco_fiscal__f811a2_idx'),
        ),
    ]
