# Generated by Django 4.2.8 on 2025-12-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_datasource_ingestrun_ingestversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryrecord",
            name="ingest_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Ingest version this record belongs to (for rollback)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salary_records",
                to="models.ingestversion",
            ),
        ),
    ]
