# Generated by Django 4.2.8 on 2025-12-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_salaryrecord_ingest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestrun',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Parsing'), (3, 'Transforming'), (4, 'Loading to Database'), (5, 'Completed')], default=0, help_text='Current pipeline stage'),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed'), (4, 'Cancelled')], default=0, help_text='Overall status of the ingest run'),
        ),
    ]
