# Generated by Django 4.2.8 on 2026-01-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_jobtitlecluster_jobtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercluster',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-safe slug for employer (e.g., 'google-llc')", max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='employercluster',
            index=models.Index(fields=['slug'], name='salary_empl_slug_5dea73_idx'),
        ),
    ]
