# Generated by Django 4.2.8 on 2026-01-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_ingestrejectionstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacutoffdate',
            name='visa_class',
            field=models.CharField(help_text='F1, F2A, EB1, EB2, etc.', max_length=100),
        ),
    ]
