# Generated by Django 4.2.8 on 2026-02-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_datasource_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='title',
            field=models.CharField(help_text='Representative job title: initially the first raw title seen; update_job_title_cluster_stats sets it to the most frequent SalaryRecord.job_title for this entity.', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobtitlecluster',
            name='canonical_title',
            field=models.CharField(db_index=True, help_text="Representative title for the cluster (e.g., 'Software Engineer'). Set by update_job_title_cluster_stats to the most frequent SalaryRecord.job_title in the cluster.", max_length=500),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employer', 'is_worksite', 'fiscal_year'], include=('wage_annual',), name='sr_emp_wk_fy_inc_wage'),
        ),
    ]
