# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_alter_jobtitle_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitlecluster',
            name='total_filings_recent',
            field=models.IntegerField(db_index=True, default=0, help_text='Filings in last N years (for autocomplete ranking); set by update_job_title_cluster_stats'),
        ),
    ]
