# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0031_salaryrecord_sr_worksite_employer"),
    ]

    operations = [
        # Expression index for ORDER BY (total_lca_count + total_perm_count) DESC, id DESC (program=all)
        migrations.RunSQL(
            sql=(
                "CREATE INDEX sec_total_filings_id ON salary_employer_cluster "
                "((total_lca_count + total_perm_count) DESC, id DESC);"
            ),
            reverse_sql="DROP INDEX IF EXISTS sec_total_filings_id;",
        ),
        # Composite indexes for program=h1b and program=perm ordering
        migrations.AddIndex(
            model_name="employercluster",
            index=models.Index(
                fields=["-total_lca_count", "id"],
                name="sec_total_lca_id",
            ),
        ),
        migrations.AddIndex(
            model_name="employercluster",
            index=models.Index(
                fields=["-total_perm_count", "id"],
                name="sec_total_perm_id",
            ),
        ),
    ]
