# Generated by Django 4.2.8 on 2026-02-07 02:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0032_employercluster_count_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFactsLedger",
            fields=[
                (
                    "fact_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this fact",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.IntegerField(
                        choices=[
                            (0, "Invalid/Unknown"),
                            (1, "USCIS I-140 Receipts (Quarterly)"),
                            (2, "DOL PERM (Lag Distribution)"),
                            (3, "DOS Annual Report"),
                        ],
                        db_index=True,
                        help_text="Source of the data (USCIS, DOL, DOS)",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. i140_receipts, visa_limit, perm_lag_distribution",
                        max_length=64,
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=dict,
                        help_text='e.g. {"country": "India", "category": "EB2"}',
                    ),
                ),
                (
                    "value",
                    models.JSONField(help_text="Raw number or distribution object"),
                ),
                (
                    "reference_period_start",
                    models.DateField(
                        help_text="Event time: start of the period this data describes (e.g. quarter start)"
                    ),
                ),
                (
                    "reference_period_end",
                    models.DateField(
                        help_text="Event time: end of the period this data describes (e.g. quarter end)"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        db_index=True,
                        help_text="Knowledge time: when this data became public (critical for backtesting)",
                    ),
                ),
            ],
            options={
                "db_table": "raw_facts_ledger",
                "ordering": ["-publication_date", "-reference_period_end"],
            },
        ),
        migrations.AddIndex(
            model_name="rawfactsledger",
            index=models.Index(
                fields=["publication_date"], name="rfl_publication_date"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfactsledger",
            index=models.Index(fields=["source", "metric"], name="rfl_source_metric"),
        ),
        migrations.AddIndex(
            model_name="rawfactsledger",
            index=models.Index(
                fields=["reference_period_start"], name="rfl_ref_period_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawfactsledger",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "metric",
                    "dimensions",
                    "reference_period_start",
                    "reference_period_end",
                ),
                name="raw_facts_ledger_unique_fact",
            ),
        ),
    ]
