# Generated by Django 4.2.8 on 2026-02-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0033_rawfactsledger_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictedBulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_bulletin_month", models.DateField(unique=True)),
                ("prediction_date", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-target_bulletin_month"],
            },
        ),
        migrations.CreateModel(
            name="PredictedCutoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visa_class", models.CharField(max_length=10)),
                ("country", models.IntegerField()),
                ("action_type", models.CharField(max_length=20)),
                ("predicted_date", models.DateField(blank=True, null=True)),
                ("confidence_low", models.DateField(blank=True, null=True)),
                ("confidence_high", models.DateField(blank=True, null=True)),
                (
                    "explanation_markdown",
                    models.TextField(blank=True, help_text="Why this prediction?"),
                ),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="employercluster",
            name="sec_total_lca_id",
        ),
        migrations.RemoveIndex(
            model_name="employercluster",
            name="sec_total_perm_id",
        ),
        migrations.AlterField(
            model_name="datasource",
            name="domain",
            field=models.CharField(
                choices=[
                    ("dol", "Department of Labor"),
                    ("visa_bulletin", "Visa Bulletin"),
                    ("uscis", "USCIS"),
                    ("dos", "Department of State"),
                ],
                help_text="Data source domain (organization/system)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("lca", "LCA (H-1B)"),
                    ("perm", "PERM (Salary)"),
                    ("worksite", "Worksite Location Data"),
                    ("bulletin", "Visa Bulletin"),
                    ("i485_inventory", "USCIS I-485 Inventory"),
                    ("issuance", "DOS Monthly Issuance"),
                    ("perm_disclosure", "PERM Disclosure (Supply)"),
                ],
                help_text="Type of data source within domain",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rawfactsledger",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "Invalid/Unknown"),
                    (1, "USCIS I-140 Receipts (Quarterly)"),
                    (2, "DOL PERM (Lag Distribution)"),
                    (3, "DOS Annual Report"),
                    (4, "USCIS I-485 Inventory"),
                    (5, "DOS Monthly Issuance"),
                    (6, "DOL PERM Disclosure"),
                ],
                db_index=True,
                help_text="Source of the data (USCIS, DOL, DOS)",
            ),
        ),
        migrations.AddField(
            model_name="predictedcutoff",
            name="bulletin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cutoffs",
                to="models.predictedbulletin",
            ),
        ),
        migrations.AddIndex(
            model_name="predictedcutoff",
            index=models.Index(
                fields=["bulletin", "visa_class", "country", "action_type"],
                name="models_pred_bulleti_55fc4a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="predictedcutoff",
            unique_together={("bulletin", "visa_class", "country", "action_type")},
        ),
    ]
