# Generated by Django 4.2.8 on 2026-02-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
