# Generated by Django 4.2.8 on 2026-03-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0037_employer_directory_partial_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employer', 'case_submitted'], name='sr_emp_case_sub'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employer', 'visa_program', 'case_submitted'], name='sr_emp_prog_case_sub'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employer', 'case_submitted', 'decision_date'], name='sr_emp_sub_dec'),
        ),
    ]
