# Generated by Django 4.2.8 on 2026-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0040_predictedcutoff_expert_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedcutoff',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text="Which model produced this prediction (e.g. 'vqs_ensemble', 'regime_switched', 'gbm_gated')", max_length=50),
        ),
    ]
