# Generated by Django 4.2.8 on 2026-03-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_predictedcutoff_movement_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedbulletin',
            name='target_bulletin_month',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='predictedbulletin',
            unique_together={('target_bulletin_month', 'prediction_date')},
        ),
    ]
