# Generated by Django 4.2.8 on 2026-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0044_employer_cluster_name_trigram_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercluster',
            name='search_avg_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Record-weighted mean wage_annual over searchable records', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employercluster',
            name='search_max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max wage_annual over searchable records', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employercluster',
            name='search_min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Min wage_annual over searchable records', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employercluster',
            name='search_record_count',
            field=models.IntegerField(default=0, help_text='Records that pass the salary-search filters for this cluster'),
        ),
    ]
