# Generated by Django 4.2.8 on 2026-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0049_widen_soc_code_to_50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('lca', 'LCA (H-1B)'), ('perm', 'PERM (Salary)'), ('worksite', 'Worksite Location Data'), ('bulletin', 'Visa Bulletin'), ('i485_inventory', 'USCIS I-485 Inventory'), ('issuance', 'DOS Monthly Issuance'), ('perm_disclosure', 'PERM Disclosure (Supply)'), ('i129', 'USCIS I-129 H-1B Petition')], help_text='Type of data source within domain', max_length=20),
        ),
    ]
