# Generated by Django 4.2.8 on 2026-06-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0050_alter_datasource_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='I129Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dol_eta_case_number', models.CharField(db_index=True, help_text='Normalized DOL ETA case number; joins to worksite_record.case_number. NOT unique — one LCA can cover multiple beneficiaries.', max_length=50)),
                ('fiscal_year', models.IntegerField(db_index=True, help_text='Lottery fiscal year (FY2021-FY2024)')),
                ('lottery_year', models.IntegerField(blank=True, help_text='Lottery year as recorded in the source row', null=True)),
                ('status_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Selected'), (2, 'Eligible (not selected)'), (3, 'Created (not selected)')], db_index=True, default=0, help_text='Lottery registration status')),
                ('ben_multi_reg_ind', models.BooleanField(db_index=True, default=False, help_text='Beneficiary had multiple registrations by different employers (gaming signal)')),
                ('first_decision', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Approved'), (2, 'Denied')], db_index=True, default=0, help_text='USCIS first decision on the petition')),
                ('first_decision_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('basis_for_classification', models.CharField(blank=True, help_text='I-129 Part 2 Q2 basis code (A=new, E=change of employer, F=amended, ...)', max_length=1)),
                ('requested_action', models.CharField(blank=True, max_length=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('i129_employer_name', models.CharField(blank=True, max_length=255)),
                ('fein', models.CharField(blank=True, db_index=True, help_text='Employer tax id (FEIN)', max_length=20)),
                ('naics_code', models.CharField(blank=True, max_length=20)),
                ('num_emp_in_us', models.IntegerField(blank=True, null=True)),
                ('h1b_dependent', models.BooleanField(blank=True, help_text='S1Q1A: petitioner is an H-1B dependent employer', null=True)),
                ('willful_violator', models.BooleanField(blank=True, help_text='S1Q1B: petitioner ever found a willful violator', null=True)),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('worksite_city', models.CharField(blank=True, max_length=100)),
                ('worksite_state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('worksite_zip', models.CharField(blank=True, max_length=10)),
                ('full_time', models.BooleanField(blank=True, null=True)),
                ('wage_amt', models.DecimalField(blank=True, decimal_places=2, help_text='Raw WAGE_AMT in the stated wage_unit', max_digits=12, null=True)),
                ('wage_unit', models.CharField(blank=True, choices=[('year', 'Per Year'), ('month', 'Per Month'), ('bi_weekly', 'Bi-Weekly'), ('week', 'Per Week'), ('hour', 'Per Hour')], max_length=20)),
                ('comp_paid_annual', models.DecimalField(blank=True, decimal_places=2, help_text='BEN_COMP_PAID — beneficiary rate of pay per year (as filed)', max_digits=12, null=True)),
                ('pay_annual', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Canonical annualized actual pay: comp_paid_annual, else WAGE_AMT annualized by wage_unit. Compare to worksite_record.wage_annual (LCA-posted).', max_digits=12, null=True)),
                ('country_of_birth', models.CharField(blank=True, db_index=True, help_text='Beneficiary country of birth (ISO3 as shipped)', max_length=80)),
                ('ben_year_of_birth', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=10)),
                ('education_code', models.CharField(blank=True, max_length=1)),
                ('ed_level', models.CharField(blank=True, max_length=120)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingest_version', models.ForeignKey(blank=True, help_text='Ingest version this record belongs to (for rollback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i129_petitions', to='models.ingestversion')),
            ],
            options={
                'db_table': 'i129_petition',
                'ordering': ['-fiscal_year', 'dol_eta_case_number'],
                'indexes': [models.Index(fields=['fiscal_year', 'first_decision'], name='i129_petiti_fiscal__1792f2_idx'), models.Index(fields=['worksite_state', 'fiscal_year'], name='i129_petiti_worksit_f08a24_idx'), models.Index(fields=['country_of_birth', 'fiscal_year'], name='i129_petiti_country_efe562_idx'), models.Index(fields=['job_title', 'worksite_state'], name='i129_petiti_job_tit_4135b3_idx'), models.Index(fields=['employer_name', 'fiscal_year'], name='i129_petiti_employe_09250a_idx'), models.Index(fields=['pay_annual'], name='i129_petiti_pay_ann_075227_idx')],
            },
        ),
    ]
