# Generated by Django 4.2.8 on 2026-07-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0052_i129_dol_eta_case_number_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='i129petition',
            name='employer_cluster',
            field=models.ForeignKey(blank=True, help_text='Resolved LCA employer cluster (populated by the employer_name→cluster linker, lib/business/i129/employer_linker.py). Lets the employer profile page scope the actual-pay comparison. NULL when no LCA cluster matched the name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i129_petitions', to='models.employercluster'),
        ),
    ]
