# Generated by Django 4.2.8 on 2026-07-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0053_i129petition_employer_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('lca', 'LCA (H-1B)'), ('perm', 'PERM (Salary)'), ('worksite', 'Worksite Location Data'), ('bulletin', 'Visa Bulletin'), ('i485_inventory', 'USCIS I-485 Inventory'), ('issuance', 'DOS Monthly Issuance'), ('perm_disclosure', 'PERM Disclosure (Supply)'), ('i129', 'USCIS I-129 H-1B Petition'), ('h1b_employer_hub', 'USCIS H-1B Employer Data Hub')], help_text='Type of data source within domain', max_length=20),
        ),
        migrations.CreateModel(
            name='UscisEmployerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(db_index=True, help_text='USCIS fiscal year')),
                ('employer_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Masked employer tax id (last 4), as shipped', max_length=20)),
                ('naics_code', models.CharField(blank=True, help_text="Industry (NAICS) — code or 'NN - Label'", max_length=120)),
                ('petitioner_city', models.CharField(blank=True, max_length=100)),
                ('petitioner_state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('petitioner_zip', models.CharField(blank=True, max_length=10)),
                ('initial_approval', models.IntegerField(default=0)),
                ('initial_denial', models.IntegerField(default=0)),
                ('continuing_approval', models.IntegerField(default=0)),
                ('continuing_denial', models.IntegerField(default=0)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_cluster', models.ForeignKey(blank=True, help_text='Resolved LCA employer cluster (employer_linker.py). NULL when no LCA cluster matched the name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uscis_approvals', to='models.employercluster')),
                ('ingest_version', models.ForeignKey(blank=True, help_text='Ingest version this record belongs to (for rollback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uscis_employer_approvals', to='models.ingestversion')),
            ],
            options={
                'db_table': 'uscis_employer_approval',
                'ordering': ['-fiscal_year', 'employer_name'],
                'indexes': [models.Index(fields=['employer_name', 'fiscal_year'], name='uscis_emplo_employe_426464_idx'), models.Index(fields=['employer_cluster', 'fiscal_year'], name='uscis_emplo_employe_febf57_idx')],
            },
        ),
    ]
