# Generated by Django 4.2.8 on 2026-08-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0056_bulletin_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_period', models.DateField(help_text="First day of the month the floor constrains (e.g. 2026-10-01). Later than the source bulletin's own month — a floor is about the future.")),
                ('visa_category', models.CharField(choices=[('family_sponsored', 'Family-Sponsored'), ('employment_based', 'Employment-Based')], help_text='Family-Sponsored or Employment-Based', max_length=20)),
                ('visa_class', models.CharField(help_text="Series class as ingested, e.g. '2nd' (matches VisaCutoffDate)", max_length=100)),
                ('action_type', models.CharField(choices=[('final_action', 'Final Action'), ('filing', 'Dates for Filing')], help_text='Which chart the floor speaks to: Final Action or Dates for Filing', max_length=20)),
                ('country', models.IntegerField(choices=[(0, 'Invalid/Unknown'), (1, 'Other Countries'), (2, 'China (mainland born)'), (3, 'India'), (4, 'Mexico'), (5, 'Philippines'), (6, 'El Salvador/Guatemala/Honduras')], help_text='Country/region for chargeability')),
                ('floor_date', models.DateField(help_text='The cutoff will not be EARLIER than this date, per the source statement')),
                ('source_quote', models.TextField(help_text='Verbatim sentence(s) from the bulletin that state the floor. Required — it is the audit trail for a hand-entered claim.')),
                ('source_section', models.CharField(blank=True, default='', help_text="Lettered note the quote came from, e.g. 'F'. Blank if unrecorded.", max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this floor was entered into the database')),
                ('source_bulletin', models.ForeignKey(help_text='The bulletin whose notes section made the statement', on_delete=django.db.models.deletion.CASCADE, related_name='published_floors', to='models.bulletin')),
            ],
            options={
                'db_table': 'published_floor',
                'ordering': ['-target_period', 'visa_class', 'country'],
                'indexes': [models.Index(fields=['visa_class', 'country', 'action_type', 'target_period'], name='pubfloor_series_target_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='publishedfloor',
            constraint=models.UniqueConstraint(fields=('source_bulletin', 'target_period', 'visa_category', 'visa_class', 'action_type', 'country'), name='uniq_published_floor_source_target_series'),
        ),
    ]
