"""
Generate two initial blog posts:
  1. "How My Prediction Model Works" — methodology explainer, category "Methodology"
  2. Analysis post for the most recent bulletin — generated by BulletinNarrator

Usage:
    bazel run //scripts/oneoff:generate_initial_blog_posts
"""

import calendar
import enum
import json
import logging
import os
import sys
from dataclasses import dataclass
from datetime import date
from statistics import median

if os.environ.get("DB_HOST") == "host.docker.internal":
    os.environ["DB_HOST"] = "localhost"

if not os.environ.get("DJANGO_SETTINGS_MODULE"):
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "django_config.settings")

import django

django.setup()

from django_config.logging_config import setup_logging  # noqa: E402
from lib.business.blog.bulletin_narrator import BulletinNarrator  # noqa: E402
from lib.utils.logging_utils import log_context  # noqa: E402
from models.blog import BlogPost  # noqa: E402
from models.bulletin import Bulletin  # noqa: E402
from models.enums.country import Country  # noqa: E402
from models.visa_cutoff_date import VisaCutoffDate  # noqa: E402
from models.vqs import PredictedCutoff  # noqa: E402

setup_logging(debug=False)
logger = logging.getLogger(__name__)

METHODOLOGY_POST_TITLE = "How My Prediction Model Works"


class ComparedModel(enum.IntEnum):
    """All models appearing in the methodology comparison table."""

    INVALID = 0
    PERSISTENCE = 1
    OPPENHEIM_PACE = 2
    DEMAND_SUPPLY_QUEUE = 3
    DASHBOARD_TREND = 4
    SEASONAL_PATTERN = 5
    MOMENTUM_3M = 6
    POLYNOMIAL_TREND = 7
    THIS_MODEL = 8


@dataclass
class ModelMetrics:
    composite_days: float  # weighted composite score (lower is better)
    mae_6m: float  # MAE at 6-month horizon (days), kept for cross-reference
    cond_dir_pct: float  # conditional directional accuracy (%)
    source_html: str  # HTML for Source / Notes cell (may include <a> tags)
    vs_persistence: float | None = None  # computed from composite vs baseline


def _get_model_metrics() -> dict[ComparedModel, ModelMetrics]:
    """Return model metrics for the comparison table.

    Composite = (0.38 × MAE_1m + 0.104 × MAE_3m + 0.40 × MAE_6m + 0.255 × MAE_12m) / 1.139
    (weights sum to 1.139; used as relative importance weights, matching MetricConfig defaults
    in accuracy_metrics.py). This is a simple per-horizon average across all 6 series —
    NOT the same as the weighted composite used in Optuna (which uses conditional_objective
    and per-sample series/regime/magnitude weighting).

    All values are directly backtested on walk-forward backtest (2016–2026, 6 series,
    horizons 1m/3m/6m/12m) via:
        ./bazel-bin/scripts/vqs/evaluate_model --horizons 1,3,6,12 --gbm --per-series-summary
    "This model" is the production dispatch (Dispatch model in evaluate_model.py).
    The composite table is now auto-generated by print_composite_table() in evaluate_model.py.
    Last evaluated: 2026-Q1 (§21 same-window eval).
    """
    raw: dict[ComparedModel, ModelMetrics] = {
        ComparedModel.PERSISTENCE: ModelMetrics(
            composite_days=195.0,
            mae_6m=229.0,
            cond_dir_pct=8.0,
            source_html="Control — predict last month's cutoff",
        ),
        ComparedModel.OPPENHEIM_PACE: ModelMetrics(
            composite_days=180.0,
            mae_6m=213.0,
            cond_dir_pct=38.0,
            source_html=(
                '<a href="https://wolfsdorf.com/chattingwithcharlie/"'
                ' target="_blank" rel="noopener">"Chatting with Charlie"</a>'
                " (Charlie Oppenheim, former DOS Chief of Visa Control);"
                " 12-month rolling average pace."
                ' <a href="https://wolfsdorf.com/delving-into-the-intricacies-of-the-final-action-chart-chart-a-and-dates-for-filing-chart-chart-b-this-legal-article-aims-to-provide-clarity-on-the-often-discussed-topic-in-our-chatting-with-ch/"'
                ' target="_blank" rel="noopener">Written methodology guide</a>.'
            ),
        ),
        ComparedModel.DEMAND_SUPPLY_QUEUE: ModelMetrics(
            composite_days=193.0,
            mae_6m=227.0,
            cond_dir_pct=69.0,
            source_html=(
                "Queue model; high direction accuracy, worse point estimate."
                ' <a href="https://agentcalc.com/green-card-priority-date-wait-time-calculator" target="_blank" rel="noopener">AgentCalc-style</a>'
                " methodology"
            ),
        ),
        ComparedModel.DASHBOARD_TREND: ModelMetrics(
            composite_days=231.0,
            mae_6m=261.0,
            cond_dir_pct=54.0,
            source_html=(
                '<a href="https://www.uscis.gov/green-card/green-card-processes-and-procedures/visa-availability-priority-dates"'
                ' target="_blank" rel="noopener">USCIS Visa Availability Dashboard</a>;'
                " 12-month moving average; commonly cited by attorneys"
            ),
        ),
        ComparedModel.SEASONAL_PATTERN: ModelMetrics(
            composite_days=199.0,
            mae_6m=235.0,
            cond_dir_pct=27.0,
            source_html=(
                "Historical median by calendar month; discussed on"
                ' <a href="https://www.reddit.com/r/USCIS_EB3/"'
                ' target="_blank" rel="noopener">r/USCIS_EB3 forums</a>'
            ),
        ),
        ComparedModel.MOMENTUM_3M: ModelMetrics(
            composite_days=298.0,
            mae_6m=331.0,
            cond_dir_pct=46.0,
            source_html=(
                "Recent pace extrapolated; fails on regime changes."
                ' Common in <a href="https://www.reddit.com/r/USCIS/" target="_blank" rel="noopener">r/USCIS</a>'
                " quick estimates"
            ),
        ),
        ComparedModel.POLYNOMIAL_TREND: ModelMetrics(
            composite_days=469.0,
            mae_6m=479.0,
            cond_dir_pct=55.0,
            source_html=(
                "Degree-2 regression on 5 years; badly extrapolates."
                ' <a href="https://visabulletintracker.com" target="_blank" rel="noopener">visabulletintracker.com</a>-style'
            ),
        ),
        ComparedModel.THIS_MODEL: ModelMetrics(
            composite_days=164.0,
            mae_6m=198.0,
            cond_dir_pct=46.0,
            source_html=(
                "Per-series dispatch: RS for China&nbsp;EB-1 (1–11m) and India&nbsp;EB-1 (1–5m);"
                " GBM Gated for India&nbsp;EB-1/China&nbsp;EB-3 at 6m and 5 series at 12m;"
                " Pace for remaining 6m/12m series; expert ensemble otherwise."
                " Beats Persistence at 6m on all 6 series (198d vs 229d avg)."
            ),
        ),
    }
    baseline = raw[ComparedModel.PERSISTENCE].composite_days
    for m in raw.values():
        m.vs_persistence = round(m.composite_days - baseline, 1)
    return raw


def _build_chart_india_eb2_history() -> str:
    """Build Plotly JSON for India EB-2 filing cutoff history (2016–present)."""
    cutoffs = list(
        VisaCutoffDate.objects.filter(
            country=Country.INDIA.value,
            visa_class="2nd",
            action_type="filing",
            bulletin__publication_date__gte=date(2016, 1, 1),
        )
        .order_by("bulletin__publication_date")
        .values("bulletin__publication_date", "cutoff_date")
    )
    if not cutoffs:
        logger.warning("_build_chart_india_eb2_history: no EB-2 India filing data found; chart will be empty")
        return "{}"

    x_dates = [str(c["bulletin__publication_date"]) for c in cutoffs]
    y_dates = [str(c["cutoff_date"]) if c["cutoff_date"] else None for c in cutoffs]

    def _make_extrap(start_date: date) -> tuple[list[str], list[str]]:
        """6-month rolling pace extrapolation starting from start_date, run to end of available data."""
        idx = next((i for i, c in enumerate(cutoffs) if c["bulletin__publication_date"] >= start_date), None)
        if idx is None or idx < 5:
            return [], []
        window = [
            (c["bulletin__publication_date"], c["cutoff_date"])
            for c in cutoffs[idx - 5 : idx + 1]
            if c["cutoff_date"]
        ]
        if len(window) < 2:
            return [], []
        pace_days = (window[-1][1] - window[0][1]).days / (len(window) - 1)
        ext_x = [str(window[-1][0])]
        ext_y = [str(window[-1][1])]
        last_pub, last_cutoff = window[-1]
        last_bulletin_date = cutoffs[-1]["bulletin__publication_date"]
        n_steps = max(
            (last_bulletin_date.year - last_pub.year) * 12
            + (last_bulletin_date.month - last_pub.month),
            0,
        )
        for _ in range(n_steps):
            m = last_pub.month + 1
            y = last_pub.year + (m - 1) // 12
            m = (m - 1) % 12 + 1
            last_pub = last_pub.replace(year=y, month=m, day=min(last_pub.day, calendar.monthrange(y, m)[1]))
            last_cutoff = date.fromordinal(last_cutoff.toordinal() + max(int(pace_days), 0))
            ext_x.append(str(last_pub))
            ext_y.append(str(last_cutoff))
        return ext_x, ext_y

    # Three historical starting points that each illustrate a different failure mode:
    # 1. Jun 2019 — flat period; extrap predicts endless flatness, misses the 2021 surge
    # 2. Sep 2021 — rapid advance; extrap predicts clearing by 2023, misses Oct retrogression
    # 3. Mar 2022 — peak before major retrogression; extrap predicts advancement, actual went backward
    extrap_configs = [
        (date(2019, 6, 1), "#f97316", "Extrap. from Jun 2019 (flat)"),
        (date(2021, 9, 1), "#dc2626", "Extrap. from Sep 2021 (rising)"),
        (date(2022, 3, 1), "#7c3aed", "Extrap. from Mar 2022 (pre-retrogression)"),
    ]
    extrap_traces = []
    for start_d, color, label in extrap_configs:
        ex, ey = _make_extrap(start_d)
        if ex:
            extrap_traces.append({
                "x": ex, "y": ey, "type": "scatter", "mode": "lines",
                "name": label,
                "line": {"color": color, "width": 1.5, "dash": "dash"},
            })

    # October annotations for fiscal year resets
    oc_x = [c for c in x_dates if c[5:7] == "10"]

    # Compute y bounds for bands to cover the full chart height
    valid_y = [y for y in y_dates if y]
    if valid_y:
        min_y_date = date.fromisoformat(min(valid_y))
        y_band_bottom = str(min_y_date.replace(year=min_y_date.year - 1))
    else:
        y_band_bottom = "2008-01-01"
    y_band_top = "2027-01-01"

    data = [
        {
            "x": x_dates, "y": y_dates, "type": "scatter", "mode": "lines",
            "name": "Actual cutoff", "line": {"color": "#2563eb", "width": 2},
        },
    ] + extrap_traces
    for ox in oc_x:
        data.append({
            "x": [ox, ox], "y": [y_band_bottom, y_band_top], "type": "scatter",
            "mode": "lines", "showlegend": False,
            "line": {"color": "rgba(239,68,68,0.15)", "width": 12},
        })
    layout = {
        "title": "India EB-2 filing cutoff: actual vs naive extrapolation",
        "xaxis": {"title": "Bulletin month", "type": "date"},
        "yaxis": {"title": "Cutoff priority date", "type": "date"},
        "legend": {"orientation": "h", "y": -0.2},
        "margin": {"l": 60, "r": 20, "t": 50, "b": 60},
        "height": 350,
        "annotations": [{"x": "2018-10-01", "y": "2018-01-01", "text": "Oct resets", "showarrow": False,
                          "font": {"color": "#dc2626", "size": 11}}],
    }
    return json.dumps({"data": data, "layout": layout})


def _build_chart_model_vs_persistence_6m() -> str:
    """Build Plotly chart comparing model 6m predictions vs 6m-lagged persistence for China EB-2.

    Uses backfilled PredictedCutoff rows where prediction_date is ~6 months before
    target_bulletin_month.  The comparison baseline is "6m-lagged persistence" — i.e. the
    actual cutoff from 6 months ago — which is what a naive "nothing will change" approach
    produces at a 6-month horizon.

    Chart covers 2018–present, which includes:
      - The advancing period 2018–2022 (where both model and persistence diverge from actual)
      - The stall/stabilisation period 2022–present (where both track actual closely)
    """
    # Actual China EB-2 filing cutoffs, full history
    cutoffs = list(
        VisaCutoffDate.objects.filter(
            country=Country.CHINA.value,
            visa_class="2nd",
            action_type="filing",
            bulletin__publication_date__gte=date(2016, 1, 1),
        )
        .order_by("bulletin__publication_date")
        .values("bulletin__publication_date", "cutoff_date")
    )

    if not cutoffs:
        logger.warning("_build_chart_model_vs_persistence_6m: no China EB-2 data; returning empty")
        return "{}"

    actual_map: dict[date, date | None] = {
        c["bulletin__publication_date"]: c["cutoff_date"] for c in cutoffs
    }
    sorted_actuals = sorted((k, v) for k, v in actual_map.items() if v is not None)

    # 6m-lagged persistence baseline: the actual value from ~6 months ago.
    # For each bulletin month, find the closest actual that is 5–7 months earlier.
    def _lag_6m(target: date) -> date | None:
        candidates = [
            (d, v) for d, v in sorted_actuals
            if 150 <= (target - d).days <= 215
        ]
        if not candidates:
            return None
        return min(candidates, key=lambda dv: abs((target - dv[0]).days - 180))[1]

    # 6m-ahead model predictions: stored predictions where the gap between
    # prediction_date and target_bulletin_month is 5–8 months.
    preds_raw = list(
        PredictedCutoff.objects.filter(
            bulletin__target_bulletin_month__gte=date(2018, 1, 1),
            country=Country.CHINA.value,
            visa_class="2nd",
            action_type="filing",
        )
        .select_related("bulletin")
        .values(
            "bulletin__target_bulletin_month",
            "bulletin__prediction_date",
            "predicted_date",
            "actual_date",
        )
    )

    pred_map: dict[date, date | None] = {}
    for row in preds_raw:
        target = row["bulletin__target_bulletin_month"]
        pred_date = row["bulletin__prediction_date"]
        gap = (target - pred_date).days
        if 150 <= gap <= 270:  # 5–9 months ahead — the 6m backfill rows
            pred_map[target] = row["predicted_date"]

    if not pred_map:
        logger.warning("_build_chart_model_vs_persistence_6m: no 6m predictions found; chart will be sparse")

    # Build chart series only for the range where we have >=10 6m predictions
    targets_with_preds = sorted(pred_map.keys())
    if not targets_with_preds:
        return "{}"

    start_date = targets_with_preds[0]
    end_date = targets_with_preds[-1]

    # Actual series restricted to the charted window
    actual_in_window = [(d, v) for d, v in sorted_actuals if start_date <= d <= end_date]
    x_actual = [str(d) for d, _ in actual_in_window]
    y_actual = [str(v) for _, v in actual_in_window]

    # Model prediction series
    model_points = sorted((t, pred_map[t]) for t in targets_with_preds if pred_map[t] is not None)
    x_model = [str(t) for t, _ in model_points]
    y_model = [str(v) for _, v in model_points]

    # 6m-lagged persistence series
    persist_points = []
    for d, _ in actual_in_window:
        lag = _lag_6m(d)
        if lag is not None:
            persist_points.append((d, lag))
    x_persist = [str(d) for d, _ in persist_points]
    y_persist = [str(v) for _, v in persist_points]

    # Compute cumulative absolute errors for annotation
    model_mae = None
    persist_mae = None
    matched = []
    for t, pred in model_points:
        actual = actual_map.get(t)
        if actual and pred:
            lag = _lag_6m(t)
            if lag:
                matched.append((abs((pred - actual).days), abs((lag - actual).days)))
    if matched:
        model_mae = round(sum(m for m, _ in matched) / len(matched))
        persist_mae = round(sum(p for _, p in matched) / len(matched))

    data = [
        {
            "x": x_actual, "y": y_actual, "type": "scatter", "mode": "lines",
            "name": "Actual cutoff",
            "line": {"color": "#2563eb", "width": 2.5},
        },
        {
            "x": x_model, "y": y_model, "type": "scatter", "mode": "lines",
            "name": "This model (6m ahead)",
            "line": {"color": "#16a34a", "width": 1.5, "dash": "dot"},
        },
        {
            "x": x_persist, "y": y_persist, "type": "scatter", "mode": "lines",
            "name": "Persistence 6m (no-change baseline)",
            "line": {"color": "#9ca3af", "width": 1.5, "dash": "dash"},
        },
    ]

    annotations = []
    if model_mae is not None and persist_mae is not None:
        improvement = round((1 - model_mae / persist_mae) * 100)
        annotations.append({
            "x": "2021-01-01", "y": "2018-01-01",
            "xref": "x", "yref": "y",
            "text": f"Model MAE: {model_mae}d<br>Persistence: {persist_mae}d<br>({improvement}% better)",
            "showarrow": False,
            "font": {"size": 10, "color": "#374151"},
            "bgcolor": "rgba(255,255,255,0.85)",
            "bordercolor": "#d1d5db",
            "borderwidth": 1,
        })

    layout = {
        "title": "China EB-2: model vs naive persistence at 6-month horizon",
        "xaxis": {"title": "Bulletin month", "type": "date"},
        "yaxis": {"title": "Cutoff priority date", "type": "date"},
        "legend": {"orientation": "h", "y": -0.25},
        "margin": {"l": 60, "r": 20, "t": 50, "b": 80},
        "height": 380,
        "annotations": annotations,
    }
    return json.dumps({"data": data, "layout": layout})


def _build_chart_seasonal_rhythm() -> str:
    """Build bar chart of median monthly India EB-2 movement by calendar month."""
    cutoffs = list(
        VisaCutoffDate.objects.filter(
            country=Country.INDIA.value,
            visa_class="2nd",
            action_type="filing",
            bulletin__publication_date__gte=date(2010, 1, 1),
        )
        .order_by("bulletin__publication_date")
        .values("bulletin__publication_date", "cutoff_date")
    )
    if len(cutoffs) < 2:
        return "{}"

    by_month: dict[int, list[int]] = {m: [] for m in range(1, 13)}
    for i in range(1, len(cutoffs)):
        cur = cutoffs[i]
        prev = cutoffs[i - 1]
        if not cur["cutoff_date"] or not prev["cutoff_date"]:
            continue
        delta = (cur["cutoff_date"] - prev["cutoff_date"]).days
        month = cur["bulletin__publication_date"].month
        by_month[month].append(delta)

    month_names = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    medians = [median(by_month[m]) if by_month[m] else 0.0 for m in range(1, 13)]

    # Color by FY phase: Oct-Dec=Q1(red), Jan-Mar=Q2(blue), Apr-Jun=Q3(blue), Jul-Sep=Q4(green)
    colors = []
    phases = []
    for m in range(1, 13):
        if m == 10:
            colors.append("#dc2626")  # October reset
            phases.append("FY reset (Oct 1 new fiscal year)")
        elif m in (7, 8, 9):
            colors.append("#16a34a")  # End-of-FY acceleration
            phases.append("End-of-FY surge (Jul–Sep)")
        else:
            colors.append("#60a5fa")  # Normal months
            phases.append("Normal")

    tooltip_texts = []
    for i, (name, val, phase) in enumerate(zip(month_names, medians, phases)):
        direction = "advance" if val > 0 else ("retrograde" if val < 0 else "no change")
        tooltip_texts.append(
            f"<b>{name}</b><br>"
            f"Median movement: {val:+.0f} days ({direction})<br>"
            f"Phase: {phase}"
        )

    # Use a minimum visible bar height so zero months still show their color.
    # Tooltip still shows the real value; only the rendered bar height is clipped.
    min_visible = max(medians) * 0.04 if max(medians) > 0 else 1.0
    display_medians = [v if abs(v) >= min_visible else (min_visible if v >= 0 else -min_visible) for v in medians]

    data = [{
        "x": month_names, "y": display_medians, "type": "bar",
        "marker": {"color": colors},
        "name": "Median advance (days)",
        "text": tooltip_texts,
        "hovertemplate": "%{text}<extra></extra>",
    }]
    layout = {
        "title": "India EB-2: median cutoff movement by calendar month (2010–present)",
        "xaxis": {"title": "Month"},
        "yaxis": {"title": "Median advance (days)"},
        "annotations": [
            {
                "x": "Oct", "y": max(medians), "text": "FY reset",
                "showarrow": True, "arrowhead": 2, "ax": 40, "ay": -30,
                "font": {"color": "#dc2626", "size": 11},
                "bgcolor": "rgba(255,255,255,0.85)", "borderpad": 3,
            },
            {
                "x": "Jul", "y": max(medians) * 0.75, "text": "End-of-FY<br>surge",
                "showarrow": True, "arrowhead": 2, "ax": -50, "ay": -40,
                "font": {"color": "#16a34a", "size": 11},
                "bgcolor": "rgba(255,255,255,0.85)", "borderpad": 3,
            },
        ],
        "margin": {"l": 60, "r": 20, "t": 50, "b": 60},
        "height": 320,
    }
    return json.dumps({"data": data, "layout": layout})


def _fmt_composite(days: float) -> str:
    return f"{int(days)}d"


def _fmt_vs_persistence(delta: float | None) -> tuple[str, str]:
    """Return (text, css_class) for the vs-persistence cell."""
    if delta is None or delta == 0.0:
        return "baseline", ""
    sign = "−" if delta < 0 else "+"
    cls = "text-success" if delta < 0 else "text-danger"
    return f"{sign}{int(abs(delta))}d", cls


def _build_methodology_content() -> str:
    """Generate full methodology post HTML, embedding Plotly charts from real DB data."""
    chart1_json = _build_chart_india_eb2_history()
    chart2_json = _build_chart_model_vs_persistence_6m()
    chart3_json = _build_chart_seasonal_rhythm()
    metrics = _get_model_metrics()

    _table_order = [
        ("Persistence (no change)", ComparedModel.PERSISTENCE, "table-light fw-bold"),
        ("Oppenheim Constant Pace", ComparedModel.OPPENHEIM_PACE, ""),
        ("Demand-Supply Queue", ComparedModel.DEMAND_SUPPLY_QUEUE, ""),
        ("12-Month Dashboard Trend", ComparedModel.DASHBOARD_TREND, ""),
        ("Seasonal Pattern", ComparedModel.SEASONAL_PATTERN, ""),
        ("3-Month Momentum", ComparedModel.MOMENTUM_3M, ""),
        ("Polynomial Trend", ComparedModel.POLYNOMIAL_TREND, ""),
        ("This model", ComparedModel.THIS_MODEL, "table-primary fw-bold"),
    ]
    _rows_html_parts = []
    _footnotes = []
    for _idx, (_label, _model_key, _tr_class) in enumerate(_table_order, start=1):
        _m = metrics[_model_key]
        _vs_text, _vs_cls = _fmt_vs_persistence(_m.vs_persistence)
        _tr_class_attr = f' class="{_tr_class}"' if _tr_class else ""
        _vs_cell_cls = f" {_vs_cls}" if _vs_cls else ""
        # Rows reference footnotes only for models that have source notes
        _fn_ref = f' <sup><a href="#fn-{_idx}" id="fnref-{_idx}">[{_idx}]</a></sup>' if _m.source_html else ""
        _rows_html_parts.append(
            f'      <tr{_tr_class_attr}>\n'
            f'        <td>{_label}{_fn_ref}</td>\n'
            f'        <td class="text-end">{_fmt_composite(_m.composite_days)}</td>\n'
            f'        <td class="text-end{_vs_cell_cls}">{_vs_text}</td>\n'
            f'        <td class="text-end">{_fmt_composite(_m.mae_6m)}</td>\n'
            f'        <td class="text-end">{int(_m.cond_dir_pct)}%</td>\n'
            "      </tr>"
        )
        if _m.source_html:
            _footnotes.append(
                f'  <li id="fn-{_idx}" class="small">'
                f'<strong>{_label}:</strong> {_m.source_html}'
                f' <a href="#fnref-{_idx}" aria-label="Back to reference">\u21a9</a></li>'
            )
    _rows_html = "\n".join(_rows_html_parts)
    _footnotes_html = (
        '<ol class="text-muted mt-2" style="font-size:0.85rem;">\n'
        + "\n".join(_footnotes)
        + "\n</ol>"
    ) if _footnotes else ""
    section4_html = (
        "<h3>4. Benchmarked Against Community Approaches</h3>\n"
        "<p>\n"
        "  The most common community approaches to predicting visa bulletin movements, measured on the same\n"
        "  walk-forward backtest (2016\u20132026, 6 series). All horizons (1m, 3m, 6m, 12m) evaluated directly.\n"
        "  \u201cThis model\u201d is the production dispatch described in Section\u00a03.\n"
        "</p>\n"
        "\n"
        '<p class="small text-muted">\n'
        "  <em>The \u201cComposite Score\u201d column is a normalized weighted average of per-horizon MAE:\n"
        "  (0.38\u00a0\u00d7\u00a0MAE 1m + 0.104\u00a0\u00d7\u00a0MAE 3m + 0.40\u00a0\u00d7\u00a0MAE 6m + 0.255\u00a0\u00d7\u00a0MAE 12m)\u00a0\u00f7\u00a01.139\n"
        "  (days of priority-date space). Lower is better.\n"
        "  All values are directly backtested on a walk-forward evaluation (2016\u20132026, 6 series).\n"
        "  \u201cDir%\u201d is direction accuracy at 6-month horizon.\n"
        "  This model wins on both composite (164d vs next-best Pace 180d) and 6m MAE (198d vs 213d),\n"
        "  but remains close to persistence at 1m where no EB-2/3 model meaningfully beats no-change.\u201d</em>\n"
        "</p>\n"
        "\n"
        '<div class="table-responsive mb-3">\n'
        '  <table class="table table-sm table-bordered" style="font-size:0.9rem;">\n'
        '    <thead class="table-light">\n'
        "      <tr>\n"
        '        <th>Method</th>\n'
        '        <th class="text-end text-nowrap">Composite</th>\n'
        '        <th class="text-end text-nowrap">vs Baseline</th>\n'
        '        <th class="text-end text-nowrap">MAE 6m</th>\n'
        '        <th class="text-end text-nowrap">Dir%</th>\n'
        "      </tr>\n"
        "    </thead>\n"
        "    <tbody>\n"
        f"{_rows_html}\n"
        "    </tbody>\n"
        "  </table>\n"
        "</div>\n"
        f"{_footnotes_html}\n"
        "\n"
        "<p>\n"
        "  \u201cDir%\u201d is conditional direction accuracy \u2014 how often the model correctly predicts whether the\n"
        "  cutoff will advance or retrogress, <em>given that it actually moves</em> (months where persistence\n"
        "  is trivially correct are excluded). The Demand-Supply model achieves the highest Dir% (67%) but\n"
        "  worse point error; the Oppenheim Pace model is the strongest single-method community baseline.\n"
        "</p>"
    )

    return f"""<div class="blog-post-content">
<p class="lead">
  With over a million people in the employment-based green card backlog, the monthly Visa Bulletin
  matters. I built this site to make waiting more transparent — and predictions more honest.
  Below is a technical description of how the prediction model works, what was tested and discarded,
  and where it still falls short.
</p>

<hr>

<h3>1. Why Linear Extrapolation Fails</h3>
<p>
  The instinctive approach is to extrapolate from recent pace. If EB-2 India advanced 30 days/month
  over the last year, project forward at that rate. The chart below shows why this breaks down
  on real data:
</p>

<div id="chart-eb2-history" style="width:100%;max-width:800px;"></div>
<script>
(function() {{
  var data = {chart1_json};
  if (data && data.data) {{
    Plotly.newPlot('chart-eb2-history', data.data, data.layout, {{responsive: true, displayModeBar: false}});
  }}
}})();
</script>

<p class="small text-muted">
  Red shaded bands mark October (fiscal year resets). Each dashed line is a 6-month rolling pace extrapolation
  launched from a different point in history: <strong>orange</strong> from Jun 2019 (predicts endless flatness — misses the 2021 surge),
  <strong>red</strong> from Sep 2021 (predicts rapid clearing — misses the retrogression that followed),
  <strong>purple</strong> from Mar 2022 (predicts continued advance — misses the major retrogression two months later).
  All three are badly wrong.
</p>

<p>
  Three structural features make Visa Bulletin cutoffs resistant to simple extrapolation:
</p>
<ul>
  <li><strong>October resets:</strong> The U.S. fiscal year starts October 1. Unused visa numbers expire
    September 30. USCIS redistributes the new allocation in October, often causing a discontinuous jump
    or retrogression — not a trend continuation.</li>
  <li><strong>Retrogression events:</strong> When USCIS approves too many cases in a prior month,
    the next bulletin must retrogress to protect the annual cap. A trend extrapolation predicts advance;
    the actual bulletin can move backward by months.</li>
  <li><strong>End-of-fiscal-year acceleration:</strong> July–September often see accelerated advancement
    as USCIS processes remaining visa numbers. This seasonal surge is predictable, but a rolling average
    treats it as noise.</li>
</ul>

<hr>

<h3>2. What We Optimize For</h3>
<p>
  This model is not optimized for a single MAE number. The actual optimization target is a weighted
  composite metric that balances several concerns:
</p>
<div class="table-responsive mb-3">
  <table class="table table-sm table-bordered">
    <thead class="table-light">
      <tr><th>Component</th><th>Raw weight</th><th>Rationale</th></tr>
    </thead>
    <tbody>
      <tr><td>1-month MAE</td><td>0.38</td><td>Will the cutoff move next month?</td></tr>
      <tr><td>6-month MAE</td><td>0.40</td><td>Where will the cutoff be mid-year?</td></tr>
      <tr><td>3-month MAE</td><td>0.104</td><td>Near-term trajectory</td></tr>
      <tr><td>12-month MAE</td><td>0.255</td><td>Annual planning horizon</td></tr>
    </tbody>
  </table>
</div>
<p class="small text-muted">
  Raw weights sum to 1.139; the composite score is their weighted average (each weight divided by 1.139),
  so the effective normalized weights are approximately 33%, 35%, 9%, 22%.
</p>
<p>
  Additional adjustments:
</p>
<ul>
  <li><strong>Series weighting:</strong> India EB-2 and EB-3 are weighted 1.5× (largest user base);
    China EB-2 at 1.2×; EB-1 series at 0.8× (smaller backlog, lower user demand).</li>
  <li><strong>Asymmetric penalty:</strong> Optimistic predictions — telling someone their date is closer
    than it really is — receive a 1.3× penalty. The model is calibrated to err on the side of caution.</li>
  <li><strong>Direction accuracy:</strong> An 8% weight on whether the model correctly predicts the
    direction of movement (advance vs. retrogression), separate from magnitude.</li>
  <li><strong>Movement-magnitude weighting:</strong> Months with large actual moves count more. We care
    about catching the big advances, not just predicting "no change."</li>
</ul>

<h4>What MAE Means in Cutoff-Date Space</h4>
<p>
  MAE is measured in days of error between the predicted cutoff date and the actual cutoff date. This is
  measured in <em>priority date space</em>, not in calendar time.
</p>
<p>
  The natural comparison baseline is <strong>6m-lagged persistence</strong>: whatever the cutoff was
  6 months ago is the "no change" forecast. During periods when cutoffs advance rapidly,
  that 6-month lag is large — a model that tracks the trend beats persistence substantially.
  The chart below shows China EB-2 from 2018. During the 2019–2022 advancing window the model
  prediction (green) stays much closer to the actual (blue) than the naive persistence baseline (grey).
  In the stall period after 2022 the three lines converge — the model correctly sees little movement.
</p>

<div id="chart-mae-example" style="width:100%;max-width:800px;"></div>
<script>
(function() {{
  var data = {chart2_json};
  if (data && data.data) {{
    Plotly.newPlot('chart-mae-example', data.data, data.layout, {{responsive: true, displayModeBar: false}});
  }}
}})();
</script>
<p class="small text-muted">
  China EB-2 filing cutoff, 2018–present. Green dashed: this model's prediction made 6 months before the
  bulletin. Grey dashed: naive "no-change" persistence from 6 months ago. The gap between grey and actual
  shows the missed advance that persistence cannot predict; the model closes much of that gap.
  Lines converge after 2022 when the series stalls — correct behaviour, not a flaw.
</p>

<hr>

<h3>3. The Model Architecture</h3>

<h4>Per-Series, Per-Horizon Dispatch</h4>
<p>
  The model routes each series to the sub-model that performs best for that series at that time horizon.
  The dispatch was determined by walk-forward backtesting across all combinations:
</p>
<div class="table-responsive mb-3">
  <table class="table table-sm table-bordered" style="font-size:0.87rem;">
    <thead class="table-light">
      <tr>
        <th>Series</th>
        <th class="text-center">1m &amp; 3m</th>
        <th class="text-center">6m</th>
        <th class="text-center">12m</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>China EB-1</td><td class="text-center">Regime-Switched</td><td class="text-center">Regime-Switched</td><td class="text-center">GBM Gated</td></tr>
      <tr><td>China EB-2</td><td class="text-center">RS (1m) / Expert Ensemble (3m)</td><td class="text-center">Pace</td><td class="text-center">GBM Gated</td></tr>
      <tr><td>China EB-3</td><td class="text-center">RS (1m) / Expert Ensemble (3m)</td><td class="text-center">GBM Gated</td><td class="text-center">GBM Gated</td></tr>
      <tr><td>India EB-1</td><td class="text-center">Regime-Switched</td><td class="text-center">GBM Gated</td><td class="text-center">GBM Gated</td></tr>
      <tr><td>India EB-2</td><td class="text-center">RS (1m) / Expert Ensemble (3m)</td><td class="text-center">Pace</td><td class="text-center">GBM Gated</td></tr>
      <tr><td>India EB-3</td><td class="text-center">RS (1m) / Expert Ensemble (3m)</td><td class="text-center">Pace</td><td class="text-center">Pace</td></tr>
    </tbody>
  </table>
</div>

<h4>Expert Ensemble (1m–3m, EB-2/3)</h4>
<p>
  For short-horizon EB-2/3 predictions, the model uses a Hedge aggregator: a collection of individual
  forecasting "experts" whose weights are updated online based on recent accuracy. Experts that have been
  accurate recently receive more weight.
</p>
<ul>
  <li><strong>Queue simulation:</strong> Demand-based model using I-140 petition counts by fiscal year and category.</li>
  <li><strong>Seasonal median:</strong> Historical median movement for each calendar month.</li>
  <li><strong>12-month linear trend:</strong> Rolling average that captures sustained advancing periods.</li>
  <li><strong>3-month momentum:</strong> Short-window signal for recent acceleration or deceleration.</li>
  <li><strong>Fiscal year cycle:</strong> Explicit model of the October reset behavior.</li>
  <li><strong>Persistence:</strong> No-change baseline, always included as a conservative anchor.</li>
</ul>
<p>
  The seasonal rhythm chart shows why explicit month-by-month modeling matters:
</p>

<div id="chart-seasonal" style="width:100%;max-width:800px;"></div>
<script>
(function() {{
  var data = {chart3_json};
  if (data && data.data) {{
    Plotly.newPlot('chart-seasonal', data.data, data.layout, {{responsive: true, displayModeBar: false}});
  }}
}})();
</script>
<p class="small text-muted">
  October (red) marks the fiscal year reset. July–September (green) show the end-of-year acceleration.
  A model that ignores these structural patterns will systematically mispredict both transitions.
</p>

<h4>GBM Gated (6m and 12m for most series)</h4>
<p>
  For longer horizons on EB-1 and most China series, the model uses a gradient-boosted machine learning
  model (GBM) with a gating mechanism trained on 10+ years of bulletin history. The GBM takes 27 features as input:
</p>
<ul>
  <li>Current cutoff date and velocity (recent pace)</li>
  <li>Monthly movement history (1m through 12m, average)</li>
  <li>Fiscal year phase (month of year, months into FY, FY boundary proximity)</li>
  <li>I-140 backlog density near the cutoff (I-485 queue)</li>
  <li>EB-1 surplus indicator (unused EB-1 visa numbers that flow to EB-2 under INA §202)</li>
  <li>ROW (rest-of-world) issuance patterns</li>
  <li>Regime classification (advancing / stalled / retrogressing / recovering / volatile)</li>
</ul>
<p>
  The GBM was tuned with Optuna across 50+ trials, and is validated on a strict walk-forward backtest:
  the model is retrained on all data available <em>before</em> each evaluation point, never using future data.
</p>

<h4>Regime-Switched (China EB-1 1–11m, India EB-1 1–5m)</h4>
<p>
  EB-1 series are structurally different: they clear rapidly near fiscal year end then retrogress,
  driven by INA §202 per-country caps and annual visa allocation rather than queue depth.
  For these series, a regime-aware persistence model that tracks the current monthly velocity
  outperforms both the expert ensemble and GBM.
</p>

<h4>Pace (6m for India EB-2/3 and China EB-2; 12m for India EB-3)</h4>
<p>
  For India EB-2, EB-3, and China EB-2 at 6 months, and India EB-3 at 12 months, the Oppenheim
  Constant Pace extrapolation (12-month rolling average velocity) outperforms the GBM.
  These series are currently in deep stall — the pace model correctly predicts minimal movement.
</p>

<hr>

{section4_html}

<details class="mb-3">
  <summary class="fw-bold small">Per-series breakdown (h=6): sub-model in parentheses</summary>
  <div class="table-responsive mt-2">
    <table class="table table-sm table-bordered" style="font-size:0.82rem;">
      <thead class="table-light">
        <tr><th>Series</th><th>Persistence</th><th>Pace</th><th>Our Model</th><th>Winner</th></tr>
      </thead>
      <tbody>
        <tr><td>China EB-1</td><td>175d</td><td>168d</td><td>158d (RS)</td><td>Our model</td></tr>
        <tr><td>China EB-2</td><td>196d</td><td>157d</td><td>157d (Pace)</td><td>Tied</td></tr>
        <tr><td>China EB-3</td><td>217d</td><td>194d</td><td>157d (GBM)</td><td>Our model</td></tr>
        <tr><td>India EB-1</td><td>292d</td><td>281d</td><td>234d (GBM)</td><td>Our model</td></tr>
        <tr><td>India EB-2</td><td>225d</td><td>215d</td><td>215d (Pace)</td><td>Tied</td></tr>
        <tr><td>India EB-3</td><td>269d</td><td>266d</td><td>266d (Pace)</td><td>Tied</td></tr>
      </tbody>
    </table>
  </div>
</details>

<h3 class="mt-4">Feature Importance: GBM Ablation Study</h3>
<p>
  To measure which inputs actually drive the GBM's predictions, we ran a <strong>feature-group ablation
  study</strong>: for each group, we zeroed out all features in that group at inference time and measured
  the change in 6-month MAE (averaged across all 6 series). The baseline MAE with all features intact
  is <strong>200d</strong>.
</p>

<div class="table-responsive mb-3">
  <table class="table table-sm table-bordered" style="font-size:0.9rem;">
    <thead class="table-light">
      <tr>
        <th class="text-nowrap">Feature Group</th>
        <th>What It Contains</th>
        <th class="text-end text-nowrap">Ablated MAE</th>
        <th class="text-end text-nowrap">&Delta; MAE</th>
        <th>Interpretation</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-nowrap"><strong>Macro / Demand</strong></td>
        <td>I-140 approval ratio, I-485 queue size, utilization rate, demand ratio, 6-month velocity</td>
        <td class="text-end text-nowrap">247d</td>
        <td class="text-end text-nowrap text-danger fw-bold">+47d</td>
        <td>Most important group &mdash; drives nearly all GBM improvement over simpler baselines</td>
      </tr>
      <tr>
        <td class="text-nowrap">Velocity</td>
        <td>1-month through 12-month moving-average cutoff movement</td>
        <td class="text-end text-nowrap">201d</td>
        <td class="text-end text-nowrap">+1d</td>
        <td>Negligible isolated impact at 6-month horizon</td>
      </tr>
      <tr>
        <td class="text-nowrap">Seasonality</td>
        <td>Month of year, FY boundary flags, months into FY</td>
        <td class="text-end text-nowrap">199d</td>
        <td class="text-end text-nowrap">&minus;1d</td>
        <td>Marginal (seasonal signal captured elsewhere)</td>
      </tr>
      <tr>
        <td class="text-nowrap">Demand Drop</td>
        <td>ROW velocity, issuance drop ratio</td>
        <td class="text-end text-nowrap">199d</td>
        <td class="text-end text-nowrap">&minus;1d</td>
        <td>Marginal at aggregate level</td>
      </tr>
      <tr>
        <td class="text-nowrap">Cross-Series</td>
        <td>EB-1 surplus, EB-1 movement signals, near-cutoff I-485 density</td>
        <td class="text-end text-nowrap">194d</td>
        <td class="text-end text-nowrap text-success">&minus;7d</td>
        <td>Model performs <em>better</em> without it &mdash; adds noise at this horizon</td>
      </tr>
    </tbody>
  </table>
</div>

<p><strong>Key findings:</strong></p>
<ul>
  <li>
    <strong>Demand signals dominate:</strong> The macro group (I-140 backlog ratio, I-485 pending queue
    density, visa utilization) accounts for essentially all of the GBM's improvement over simpler
    baselines like Oppenheim Pace or persistence. Without these features, the GBM degrades by 47 days.
  </li>
  <li>
    <strong>Cross-series signals hurt at 6 months:</strong> The statutory EB-1 &rarr; EB-2 overflow rule
    is real (INA &sect;203), but the GBM picks up noise from the EB-1 surplus features at this horizon.
    This is consistent with findings that EB-1 spillover only clearly predicts EB-2/3 movement at shorter
    (1&ndash;3 month) windows for some series.
  </li>
  <li>
    <strong>Velocity and seasonality are redundant at GBM level:</strong> These features matter for the
    1-month expert ensemble (where seasonal rhythm and recent momentum are primary signals), but the GBM
    at 6&ndash;12 months gets more value from structural demand indicators.
  </li>
</ul>

<hr>

<h3>5. What Was Tested and Rejected</h3>
<ul>
  <li>
    <strong>Fiscal year conditional models:</strong> Separate experts for FY boundary months vs. steady-state.
    Insufficient training data (~8 transitions per series).
  </li>
  <li>
    <strong>Hardcoded regime dispatch:</strong> "If advancing, use demand signal; if stalled, use persistence."
    Cannot be tuned and does not generalize across series. Replaced by trainable Hedge weights.
  </li>
  <li>
    <strong>GBM at 1-month horizon as point predictor:</strong> The base-rate problem: ~80% of months have
    no significant movement for EB-2/3. The GBM predicts spurious moves. Used only for movement probability
    classification, not as a point predictor.
  </li>
  <li>
    <strong>PERM filing volume:</strong> Hypothesized as a 12–18 month leading indicator of EB-2/3 demand.
    Feature ablation (zeroing the feature at inference) showed the GBM trees did not use it in any
    decision path. The apparent improvement was from accumulating more training data.
  </li>
</ul>

<hr>

<h3>6. Known Limitations</h3>
<ul>
  <li><strong>India EB-3:</strong> The cutoff has barely moved in years. The structural backlog makes
    any 6-month prediction inherently uncertain. Confidence intervals are wide; directional guidance
    is more reliable than point estimates.</li>
  <li><strong>Retrogression events:</strong> When USCIS must retrogress to protect the cap, it is typically
    not predictable from historical patterns. The model will under-predict these events.</li>
  <li><strong>Policy shocks:</strong> Congressional action, USCIS fee changes, and I-140 filing surges
    before policy deadlines are not predictable from the visa bulletin data alone.</li>
</ul>

<p class="small text-muted mt-3">
  Monthly analysis posts compare predictions to actual bulletins. See
  <a href="/analysis/">recent analyses</a> or
  <a href="/predictions/employment_based/">historical prediction accuracy</a>.
</p>
</div>"""


def create_methodology_post() -> BlogPost:
    """Insert or update the methodology explainer blog post with real data charts."""
    from django.utils.text import slugify

    slug = slugify(METHODOLOGY_POST_TITLE)
    content = _build_methodology_content()
    post, created = BlogPost.objects.update_or_create(
        slug=slug,
        defaults={
            "title": METHODOLOGY_POST_TITLE,
            "content": content,
            "is_published": True,
            "category": "Methodology",
            "related_bulletin": None,
        },
    )
    action = "Created" if created else "Updated"
    logger.info("%s methodology post: '%s' (slug: %s)", action, post.title, post.slug)
    return post


def create_analysis_posts(n: int = 2) -> list[BlogPost]:
    """Generate analysis posts for the N most recently ingested bulletins.

    Deletes any existing analysis posts for bulletins not in the top N.
    """
    bulletins = list(Bulletin.objects.order_by("-publication_date")[:n])
    if not bulletins:
        logger.warning("No bulletins found in DB — skipping analysis posts.")
        return []

    narrator = BulletinNarrator()
    created_slugs = set()
    posts = []
    for bulletin in bulletins:
        logger.info("Generating analysis post for bulletin %s", bulletin.publication_date)
        post = narrator.generate_post_for_bulletin(bulletin)
        logger.info("Generated analysis post: '%s' (slug: %s)", post.title, post.slug)
        created_slugs.add(post.slug)
        posts.append(post)

    # Remove stale analysis posts that are no longer in the top N
    stale = BlogPost.objects.filter(category="Analysis").exclude(slug__in=created_slugs)
    stale_count = stale.count()
    if stale_count:
        logger.info("Deleting %d stale analysis post(s).", stale_count)
        stale.delete()

    return posts


def main() -> None:
    log_context("Generating blog posts: methodology explainer + 2 most recent bulletin analyses")
    logger.info("=== Generating Blog Posts ===")

    methodology_post = create_methodology_post()
    logger.info("Methodology post slug: %s", methodology_post.slug)

    analysis_posts = create_analysis_posts(n=2)
    for post in analysis_posts:
        logger.info("Analysis post slug: %s", post.slug)

    logger.info("Done. Posts are published and visible at /analysis/")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logger.exception("Failed to generate initial blog posts")
        sys.exit(1)
