"""
Generate two initial blog posts:
  1. "How My Prediction Model Works" — methodology explainer, category "Methodology"
  2. Analysis post for the most recent bulletin — generated by BulletinNarrator

Usage:
    bazel run //scripts/oneoff:generate_initial_blog_posts
"""

import json
import logging
import os
import sys
from datetime import date
from statistics import median

if os.environ.get("DB_HOST") == "host.docker.internal":
    os.environ["DB_HOST"] = "localhost"

if not os.environ.get("DJANGO_SETTINGS_MODULE"):
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "django_config.settings")

import django

django.setup()

from django_config.logging_config import setup_logging  # noqa: E402
from lib.business.blog.bulletin_narrator import BulletinNarrator  # noqa: E402
from lib.utils.logging_utils import log_context  # noqa: E402
from models.blog import BlogPost  # noqa: E402
from models.bulletin import Bulletin  # noqa: E402
from models.enums.country import Country  # noqa: E402
from models.visa_cutoff_date import VisaCutoffDate  # noqa: E402
from models.vqs import PredictedCutoff  # noqa: E402

setup_logging(debug=False)
logger = logging.getLogger(__name__)

METHODOLOGY_POST_TITLE = "How My Prediction Model Works"


def _build_chart_india_eb2_history() -> str:
    """Build Plotly JSON for India EB-2 filing cutoff history (2016–present)."""
    cutoffs = list(
        VisaCutoffDate.objects.filter(
            country=Country.INDIA.value,
            visa_class="2nd",
            action_type="filing",
            bulletin__publication_date__gte=date(2016, 1, 1),
        )
        .order_by("bulletin__publication_date")
        .values("bulletin__publication_date", "cutoff_date")
    )
    if not cutoffs:
        return "{}"

    x_dates = [str(c["bulletin__publication_date"]) for c in cutoffs]
    y_dates = [str(c["cutoff_date"]) if c["cutoff_date"] else None for c in cutoffs]

    # Extrapolation: last 3 months pace projected 2 years
    last_n = 6
    valid = [(c["bulletin__publication_date"], c["cutoff_date"]) for c in cutoffs[-last_n:] if c["cutoff_date"]]
    if len(valid) >= 2:
        pace_days = (valid[-1][1] - valid[0][1]).days / (len(valid) - 1)
        extrap_x, extrap_y = [str(valid[-1][0])], [str(valid[-1][1])]
        last_pub = valid[-1][0]
        last_cutoff = valid[-1][1]
        import calendar
        for _ in range(24):
            m = last_pub.month + 1
            y = last_pub.year + (m - 1) // 12
            m = (m - 1) % 12 + 1
            last_pub = last_pub.replace(year=y, month=m, day=min(last_pub.day, calendar.monthrange(y, m)[1]))
            new_days = last_cutoff.toordinal() + int(pace_days)
            last_cutoff = date.fromordinal(min(new_days, date(2026, 3, 1).toordinal()))
            extrap_x.append(str(last_pub))
            extrap_y.append(str(last_cutoff))
    else:
        extrap_x, extrap_y = [], []

    # October annotations for fiscal year resets
    oc_x = [c for c in x_dates if c[5:7] == "10"]

    data = [
        {
            "x": x_dates, "y": y_dates, "type": "scatter", "mode": "lines",
            "name": "Actual cutoff", "line": {"color": "#2563eb", "width": 2},
        },
        {
            "x": extrap_x, "y": extrap_y, "type": "scatter", "mode": "lines",
            "name": "Naive extrapolation", "line": {"color": "#dc2626", "width": 1.5, "dash": "dash"},
        },
    ]
    for ox in oc_x[:8]:
        data.append({
            "x": [ox, ox], "y": ["2012-01-01", "2026-01-01"], "type": "scatter",
            "mode": "lines", "showlegend": False,
            "line": {"color": "rgba(239,68,68,0.15)", "width": 12},
        })
    layout = {
        "title": "India EB-2 filing cutoff: actual vs naive extrapolation",
        "xaxis": {"title": "Bulletin month", "type": "date"},
        "yaxis": {"title": "Cutoff priority date", "type": "date"},
        "legend": {"orientation": "h", "y": -0.2},
        "margin": {"l": 60, "r": 20, "t": 50, "b": 60},
        "height": 350,
        "annotations": [{"x": "2018-10-01", "y": "2018-01-01", "text": "Oct resets", "showarrow": False,
                          "font": {"color": "#dc2626", "size": 11}}],
    }
    return json.dumps({"data": data, "layout": layout})


def _build_chart_mae_explanation() -> str:
    """Build Plotly chart showing MAE examples on China EB-2 predictions vs actual."""
    cutoffs = list(
        VisaCutoffDate.objects.filter(
            country=Country.CHINA.value,
            visa_class="2nd",
            action_type="filing",
            bulletin__publication_date__range=(date(2021, 1, 1), date(2024, 12, 1)),
        )
        .order_by("bulletin__publication_date")
        .values("bulletin__publication_date", "cutoff_date")
    )
    preds_6m = list(
        PredictedCutoff.objects.filter(
            bulletin__target_bulletin_month__range=(date(2021, 7, 1), date(2025, 6, 1)),
            country=Country.CHINA.value,
            visa_class="2nd",
            action_type="filing",
        )
        .select_related("bulletin")
        .values("bulletin__target_bulletin_month", "predicted_date", "bulletin__generated_at")
    )

    actual_map = {c["bulletin__publication_date"]: c["cutoff_date"] for c in cutoffs if c["cutoff_date"]}

    x_actual = [str(k) for k in sorted(actual_map)]
    y_actual = [str(actual_map[k]) for k in sorted(actual_map)]

    # Build 6-month-ahead prediction line: match prediction made 6m before target
    pred_points = []
    for p in preds_6m:
        t = p["bulletin__target_bulletin_month"]
        if t in actual_map:
            pred_points.append((t, p["predicted_date"]))
    pred_points.sort()

    x_pred = [str(t) for t, _ in pred_points]
    y_pred = [str(pd) if pd else None for _, pd in pred_points]

    # Persistence: previous month's actual cutoff
    sorted_actual = sorted(actual_map.items())
    x_persist, y_persist = [], []
    for i in range(1, len(sorted_actual)):
        x_persist.append(str(sorted_actual[i][0]))
        y_persist.append(str(sorted_actual[i - 1][1]))

    data = [
        {"x": x_actual, "y": y_actual, "type": "scatter", "mode": "lines",
         "name": "Actual", "line": {"color": "#2563eb", "width": 2}},
        {"x": x_pred, "y": y_pred, "type": "scatter", "mode": "lines",
         "name": "VQS 6m prediction", "line": {"color": "#16a34a", "width": 1.5, "dash": "dot"}},
        {"x": x_persist, "y": y_persist, "type": "scatter", "mode": "lines",
         "name": "Persistence (no change)", "line": {"color": "#9ca3af", "width": 1, "dash": "dash"}},
    ]
    layout = {
        "title": "China EB-2: actual vs 6-month predictions",
        "xaxis": {"title": "Bulletin month", "type": "date"},
        "yaxis": {"title": "Cutoff priority date", "type": "date"},
        "legend": {"orientation": "h", "y": -0.2},
        "margin": {"l": 60, "r": 20, "t": 50, "b": 60},
        "height": 350,
    }
    return json.dumps({"data": data, "layout": layout})


def _build_chart_seasonal_rhythm() -> str:
    """Build bar chart of median monthly India EB-2 movement by calendar month."""
    cutoffs = list(
        VisaCutoffDate.objects.filter(
            country=Country.INDIA.value,
            visa_class="2nd",
            action_type="filing",
            bulletin__publication_date__gte=date(2010, 1, 1),
        )
        .order_by("bulletin__publication_date")
        .values("bulletin__publication_date", "cutoff_date")
    )
    if len(cutoffs) < 2:
        return "{}"

    by_month: dict[int, list[int]] = {m: [] for m in range(1, 13)}
    for i in range(1, len(cutoffs)):
        cur = cutoffs[i]
        prev = cutoffs[i - 1]
        if not cur["cutoff_date"] or not prev["cutoff_date"]:
            continue
        delta = (cur["cutoff_date"] - prev["cutoff_date"]).days
        month = cur["bulletin__publication_date"].month
        by_month[month].append(delta)

    month_names = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    medians = [median(by_month[m]) if by_month[m] else 0.0 for m in range(1, 13)]

    # Color by FY phase: Oct-Dec=Q1(red), Jan-Mar=Q2(blue), Apr-Jun=Q3(blue), Jul-Sep=Q4(green)
    colors = []
    for m in range(1, 13):
        if m == 10:
            colors.append("#dc2626")  # October reset
        elif m in (7, 8, 9):
            colors.append("#16a34a")  # End-of-FY acceleration
        else:
            colors.append("#60a5fa")  # Normal months

    data = [{
        "x": month_names, "y": medians, "type": "bar",
        "marker": {"color": colors},
        "name": "Median advance (days)",
    }]
    layout = {
        "title": "India EB-2: median cutoff movement by calendar month (2010–present)",
        "xaxis": {"title": "Month"},
        "yaxis": {"title": "Median advance (days)"},
        "annotations": [
            {"x": "Oct", "y": max(medians) * 0.9, "text": "FY reset", "showarrow": False,
             "font": {"color": "#dc2626", "size": 11}},
            {"x": "Sep", "y": max(medians) * 0.85, "text": "End-of-FY surge", "showarrow": False,
             "font": {"color": "#16a34a", "size": 11}},
        ],
        "margin": {"l": 60, "r": 20, "t": 50, "b": 60},
        "height": 320,
    }
    return json.dumps({"data": data, "layout": layout})


def _build_methodology_content() -> str:
    """Generate full methodology post HTML, embedding Plotly charts from real DB data."""
    chart1_json = _build_chart_india_eb2_history()
    chart2_json = _build_chart_mae_explanation()
    chart3_json = _build_chart_seasonal_rhythm()

    return f"""<div class="blog-post-content">
<p class="lead">
  With over a million people in the employment-based green card backlog, the monthly Visa Bulletin
  matters. I built this site to make waiting more transparent — and predictions more honest.
  Below is a technical description of how the prediction model works, what was tested and discarded,
  and where it still falls short.
</p>

<hr>

<h3>1. Why Linear Extrapolation Fails</h3>
<p>
  The instinctive approach is to extrapolate from recent pace. If EB-2 India advanced 30 days/month
  over the last year, project forward at that rate. The chart below shows why this breaks down
  on real data:
</p>

<div id="chart-eb2-history" style="width:100%;max-width:800px;"></div>
<script>
(function() {{
  var data = {chart1_json};
  if (data && data.data) {{
    Plotly.newPlot('chart-eb2-history', data.data, data.layout, {{responsive: true, displayModeBar: false}});
  }}
}})();
</script>

<p class="small text-muted">
  Red shaded bands mark October (fiscal year resets). The dashed red line shows what a 6-month rolling pace
  extrapolation would predict. The extrapolation misses the October FY reset, the retrogression events,
  and the end-of-fiscal-year acceleration in August–September.
</p>

<p>
  Three structural features make Visa Bulletin cutoffs resistant to simple extrapolation:
</p>
<ul>
  <li><strong>October resets:</strong> The U.S. fiscal year starts October 1. Unused visa numbers expire
    September 30. USCIS redistributes the new allocation in October, often causing a discontinuous jump
    or retrogression — not a trend continuation.</li>
  <li><strong>Retrogression events:</strong> When USCIS approves too many cases in a prior month,
    the next bulletin must retrogress to protect the annual cap. A trend extrapolation predicts advance;
    the actual bulletin can move backward by months.</li>
  <li><strong>End-of-fiscal-year acceleration:</strong> July–September often see accelerated advancement
    as USCIS processes remaining visa numbers. This seasonal surge is predictable, but a rolling average
    treats it as noise.</li>
</ul>

<hr>

<h3>2. What We Optimize For</h3>
<p>
  This model is not optimized for a single MAE number. The actual optimization target is a weighted
  composite metric that balances several concerns:
</p>
<div class="table-responsive mb-3">
  <table class="table table-sm table-bordered">
    <thead class="table-light">
      <tr><th>Component</th><th>Weight</th><th>Rationale</th></tr>
    </thead>
    <tbody>
      <tr><td>1-month MAE</td><td>38%</td><td>Will the cutoff move next month?</td></tr>
      <tr><td>6-month MAE</td><td>40%</td><td>Where will the cutoff be mid-year?</td></tr>
      <tr><td>3-month MAE</td><td>10%</td><td>Near-term trajectory</td></tr>
      <tr><td>12-month MAE</td><td>26%</td><td>Annual planning horizon</td></tr>
    </tbody>
  </table>
</div>
<p>
  Additional adjustments:
</p>
<ul>
  <li><strong>Series weighting:</strong> India EB-2 and EB-3 are weighted 1.5× (largest user base);
    China EB-2 at 1.2×; EB-1 series at 0.8× (smaller backlog, lower user demand).</li>
  <li><strong>Asymmetric penalty:</strong> Optimistic predictions — telling someone their date is closer
    than it really is — receive a 1.3× penalty. The model is calibrated to err on the side of caution.</li>
  <li><strong>Direction accuracy:</strong> An 8% weight on whether the model correctly predicts the
    direction of movement (advance vs. retrogression), separate from magnitude.</li>
  <li><strong>Movement-magnitude weighting:</strong> Months with large actual moves count more. We care
    about catching the big advances, not just predicting "no change."</li>
</ul>

<h4>What MAE Means in Cutoff-Date Space</h4>
<p>
  MAE is measured in days of error between the predicted cutoff date and the actual cutoff date. This is
  measured in <em>priority date space</em>, not in calendar time.
</p>
<p>
  Concrete example: India EB-2 cutoff is at 01-Jan-2013. The model predicts 01-Jul-2013 for 6 months
  from now. The actual result is 01-Feb-2013 — the cutoff only advanced 31 days. The model's error is
  <strong>181 days</strong> — not because it was off by 6 months of real time, but because priority dates
  from mid-2013 are still years away from being current.
</p>
<p>
  The relevant comparison is always the persistence baseline ("no change"): a model that predicts the
  same cutoff as last month. If persistence has MAE of 230 days at 6 months and the model has MAE of
  210 days, the model is reducing error by ~9% — modest, but measurable. India EB-3, where the cutoff
  has barely moved in years, is the hardest series: even the persistence baseline has low MAE because
  nothing moves.
</p>

<div id="chart-mae-example" style="width:100%;max-width:800px;"></div>
<script>
(function() {{
  var data = {chart2_json};
  if (data && data.data) {{
    Plotly.newPlot('chart-mae-example', data.data, data.layout, {{responsive: true, displayModeBar: false}});
  }}
}})();
</script>

<hr>

<h3>3. The Model Architecture</h3>

<h4>1-Month Horizon: Expert Ensemble</h4>
<p>
  For 1-month predictions, the model uses a Hedge aggregator: a collection of individual forecasting
  "experts" whose weights are updated online based on recent accuracy. Experts that have been accurate
  recently receive more weight. The aggregated prediction is a weighted average of expert predictions.
</p>
<ul>
  <li><strong>Queue simulation:</strong> Demand-based model using I-140 petition counts by fiscal year and category.</li>
  <li><strong>Seasonal median:</strong> Historical median movement for each calendar month.</li>
  <li><strong>12-month linear trend:</strong> Rolling average that captures sustained advancing periods.</li>
  <li><strong>3-month momentum:</strong> Short-window signal for recent acceleration or deceleration.</li>
  <li><strong>Fiscal year cycle:</strong> Explicit model of the October reset behavior.</li>
  <li><strong>Persistence:</strong> No-change baseline, always included as a conservative anchor.</li>
</ul>
<p>
  The seasonal rhythm chart shows why explicit month-by-month modeling matters:
</p>

<div id="chart-seasonal" style="width:100%;max-width:800px;"></div>
<script>
(function() {{
  var data = {chart3_json};
  if (data && data.data) {{
    Plotly.newPlot('chart-seasonal', data.data, data.layout, {{responsive: true, displayModeBar: false}});
  }}
}})();
</script>
<p class="small text-muted">
  October (red) marks the fiscal year reset. July–September (green) show the end-of-year acceleration.
  A model that ignores these structural patterns will systematically mispredict both transitions.
</p>

<h4>6-Month and 12-Month Horizon: Gradient Boosted Trees</h4>
<p>
  For longer horizons, the model switches to a gradient-boosted machine learning model (GBM) trained on
  10+ years of bulletin history. The GBM takes 27 features as input:
</p>
<ul>
  <li>Current cutoff date and velocity (recent pace)</li>
  <li>Monthly movement history (1m through 12m, average)</li>
  <li>Fiscal year phase (month of year, months into FY, FY boundary proximity)</li>
  <li>I-140 backlog density near the cutoff (I-485 queue)</li>
  <li>EB-1 surplus indicator (unused EB-1 visa numbers that flow to EB-2 under INA §202)</li>
  <li>ROW (rest-of-world) issuance patterns</li>
  <li>Regime classification (advancing / stalled / retrogressing / recovering / volatile)</li>
</ul>
<p>
  The GBM was tuned with Optuna across 50+ trials, and is validated on a strict walk-forward backtest:
  the model is retrained on all data available <em>before</em> each evaluation point, never using future data.
</p>

<hr>

<h3>4. Benchmarked Against Community Approaches</h3>
<p>
  The most common community approaches to predicting visa bulletin movements, measured on the same
  walk-forward backtest (h=6 month horizon, 2016–2025, 6 series):
</p>

<div class="table-responsive mb-3">
  <table class="table table-sm table-bordered">
    <thead class="table-light">
      <tr>
        <th>Method</th>
        <th class="text-end">Avg MAE 6m</th>
        <th class="text-end">vs Persistence</th>
        <th class="text-end">CondDir%</th>
        <th>Source / Notes</th>
      </tr>
    </thead>
    <tbody>
      <tr class="table-light fw-bold">
        <td>Persistence (no change)</td>
        <td class="text-end">230d</td>
        <td class="text-end">baseline</td>
        <td class="text-end">15%</td>
        <td>Control — predict last month's cutoff</td>
      </tr>
      <tr>
        <td>Oppenheim Constant Pace</td>
        <td class="text-end">213d</td>
        <td class="text-end text-success">−17d</td>
        <td class="text-end">37%</td>
        <td>DOS "Chats with Charlie" methodology; 12-month rolling average pace</td>
      </tr>
      <tr>
        <td>Demand-Supply Queue</td>
        <td class="text-end">224d</td>
        <td class="text-end text-success">−6d</td>
        <td class="text-end">66%</td>
        <td>AgentCalc-style queue model; high direction accuracy, worse point estimate</td>
      </tr>
      <tr>
        <td>12-Month Dashboard Trend</td>
        <td class="text-end">257d</td>
        <td class="text-end text-danger">+27d</td>
        <td class="text-end">54%</td>
        <td>USCIS "Dashboard" 12-month moving average; commonly cited by attorneys</td>
      </tr>
      <tr>
        <td>Seasonal Pattern</td>
        <td class="text-end">236d</td>
        <td class="text-end text-danger">+6d</td>
        <td class="text-end">25%</td>
        <td>Historical median by calendar month (Trackitt forums)</td>
      </tr>
      <tr>
        <td>3-Month Momentum</td>
        <td class="text-end">326d</td>
        <td class="text-end text-danger">+96d</td>
        <td class="text-end">47%</td>
        <td>r/USCIS quick estimates; recent pace extrapolated; fails on regime changes</td>
      </tr>
      <tr>
        <td>Polynomial Trend</td>
        <td class="text-end">471d</td>
        <td class="text-end text-danger">+241d</td>
        <td class="text-end">55%</td>
        <td>Degree-2 regression on 5 years; visabulletintracker.com-style; badly extrapolates</td>
      </tr>
      <tr class="table-primary fw-bold">
        <td>This model (best variant)</td>
        <td class="text-end">212d</td>
        <td class="text-end text-success">−18d</td>
        <td class="text-end">40%</td>
        <td>Hybrid ensemble; wins on 6/6 series vs persistence</td>
      </tr>
    </tbody>
  </table>
</div>

<p>
  "CondDir%" is conditional direction accuracy — how often the model correctly predicts whether the
  cutoff will advance or retrogress, <em>given that it actually moves</em> (months where persistence
  is trivially correct are excluded). The Demand-Supply model achieves the highest CondDir (66%) but
  worse point error; the Oppenheim Pace model is the strongest single-method community baseline.
</p>

<details class="mb-3">
  <summary class="fw-bold small">Per-series breakdown (h=6)</summary>
  <div class="table-responsive mt-2">
    <table class="table table-sm table-bordered" style="font-size:0.82rem;">
      <thead class="table-light">
        <tr><th>Series</th><th>Persistence</th><th>Pace</th><th>Our Model</th><th>Winner</th></tr>
      </thead>
      <tbody>
        <tr><td>China EB-1</td><td>175d</td><td>161d</td><td>159d</td><td>Our model</td></tr>
        <tr><td>China EB-2</td><td>195d</td><td>154d</td><td>154d</td><td>Tied</td></tr>
        <tr><td>China EB-3</td><td>223d</td><td>199d</td><td>199d</td><td>Tied</td></tr>
        <tr><td>India EB-1</td><td>286d</td><td>270d</td><td>267d</td><td>Our model</td></tr>
        <tr><td>India EB-2</td><td>215d</td><td>208d</td><td>208d</td><td>Tied</td></tr>
        <tr><td>India EB-3</td><td>289d</td><td>283d</td><td>283d</td><td>Tied</td></tr>
      </tbody>
    </table>
  </div>
</details>

<hr>

<h3>5. What Was Tested and Rejected</h3>
<ul>
  <li>
    <strong>Fiscal year conditional models:</strong> Separate experts for FY boundary months vs. steady-state.
    Insufficient training data (~8 transitions per series).
  </li>
  <li>
    <strong>Hardcoded regime dispatch:</strong> "If advancing, use demand signal; if stalled, use persistence."
    Cannot be tuned and does not generalize across series. Replaced by trainable Hedge weights.
  </li>
  <li>
    <strong>GBM at 1-month horizon as point predictor:</strong> The base-rate problem: ~80% of months have
    no significant movement for EB-2/3. The GBM predicts spurious moves. Used only for movement probability
    classification, not as a point predictor.
  </li>
  <li>
    <strong>PERM filing volume:</strong> Hypothesized as a 12–18 month leading indicator of EB-2/3 demand.
    Feature ablation (zeroing the feature at inference) showed the GBM trees did not use it in any
    decision path. The apparent improvement was from accumulating more training data.
  </li>
</ul>

<hr>

<h3>6. Known Limitations</h3>
<ul>
  <li><strong>India EB-3:</strong> The cutoff has barely moved in years. The structural backlog makes
    any 6-month prediction inherently uncertain. Confidence intervals are wide; directional guidance
    is more reliable than point estimates.</li>
  <li><strong>Retrogression events:</strong> When USCIS must retrogress to protect the cap, it is typically
    not predictable from historical patterns. The model will under-predict these events.</li>
  <li><strong>Policy shocks:</strong> Congressional action, USCIS fee changes, and I-140 filing surges
    before policy deadlines are not predictable from the visa bulletin data alone.</li>
</ul>

<p class="small text-muted mt-3">
  Monthly analysis posts compare predictions to actual bulletins. See
  <a href="/analysis/">recent analyses</a> or
  <a href="/predictions/employment_based/">historical prediction accuracy</a>.
</p>
</div>"""


def create_methodology_post() -> BlogPost:
    """Insert or update the methodology explainer blog post with real data charts."""
    from django.utils.text import slugify

    slug = slugify(METHODOLOGY_POST_TITLE)
    content = _build_methodology_content()
    post, created = BlogPost.objects.update_or_create(
        slug=slug,
        defaults={
            "title": METHODOLOGY_POST_TITLE,
            "content": content,
            "is_published": True,
            "category": "Methodology",
            "related_bulletin": None,
        },
    )
    action = "Created" if created else "Updated"
    logger.info("%s methodology post: '%s' (slug: %s)", action, post.title, post.slug)
    return post


def create_analysis_posts(n: int = 2) -> list[BlogPost]:
    """Generate analysis posts for the N most recently ingested bulletins.

    Deletes any existing analysis posts for bulletins not in the top N.
    """
    bulletins = list(Bulletin.objects.order_by("-publication_date")[:n])
    if not bulletins:
        logger.warning("No bulletins found in DB — skipping analysis posts.")
        return []

    narrator = BulletinNarrator()
    created_slugs = set()
    posts = []
    for bulletin in bulletins:
        logger.info("Generating analysis post for bulletin %s", bulletin.publication_date)
        post = narrator.generate_post_for_bulletin(bulletin)
        logger.info("Generated analysis post: '%s' (slug: %s)", post.title, post.slug)
        created_slugs.add(post.slug)
        posts.append(post)

    # Remove stale analysis posts that are no longer in the top N
    stale = BlogPost.objects.filter(category="Analysis").exclude(slug__in=created_slugs)
    stale_count = stale.count()
    if stale_count:
        logger.info("Deleting %d stale analysis post(s).", stale_count)
        stale.delete()

    return posts


def main() -> None:
    log_context("Generating blog posts: methodology explainer + 2 most recent bulletin analyses")
    logger.info("=== Generating Blog Posts ===")

    methodology_post = create_methodology_post()
    logger.info("Methodology post slug: %s", methodology_post.slug)

    analysis_posts = create_analysis_posts(n=2)
    for post in analysis_posts:
        logger.info("Analysis post slug: %s", post.slug)

    logger.info("Done. Posts are published and visible at /analysis/")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logger.exception("Failed to generate initial blog posts")
        sys.exit(1)
