# Build file for test data files

filegroup(
    name = "dol_golden_test_data",
    srcs = ["dol_golden_test_data.yaml"],
    visibility = ["//visibility:public"],
)

exports_files([
    "unknown_file_types.txt",
])

